<?php

namespace App\Requests;

use Validator;

class AberturaDeContratoRule {

    public static $endpoint = 'DadosContrato_I012';

    protected static $request = [
        'GUID'                        => '',
        'DADOS_CONTRATO'              => [
            'COD_INTERF'              => '',
            'TIPO_ORDEM'              => '',
            'EMISSOR'                 => '',
            'KUNNR_EMISSOR'           => '',
            'PAGADOR'                 => '',
            'KUNNR_PAGADOR'           => '',
            'AGENCIA'                 => '',
            'KUNNR_AGENCIA'           => '',
            'AG_TRIPARTITE'           => '',
            'KUNNR_AG_TRIPARTITE'     => '',
            'COND_ADICIONAL'          => '',
            'KUNNR_COND_ADICIONAL'    => '',
            'AG_ABERTURA'             => '',
            'PERNR_AG_ABERTURA'       => '',
            'AG_ENCERRAMENTO'         => '',
            'PERNR_AG_ENCERRAMENTO'   => '',
            'ZZUPGRADE'               => '',
            'ZZNRCONTRATO'            => '',
            'ZZNRPERIODO'             => '',
            'ZZNRADITIVO'             => '',
            'ZZNRRESERVA'             => '',
            'ZZTPCANAL'               => '',
            'ZZCODREF'                => '',
            'ZZDTARES'                => '',
            'ZZHRARES'                => '',
            'ZZLJRET'                 => '',
            'ZZDTARET'                => '',
            'ZZHRARET'                => '',
            'ZZPLACARET'              => '',
            'ZZGPRET'                 => '',
            'ZZLJDEV'                 => '',
            'ZZDTADEV'                => '',
            'ZZHRADEV'                => '',
            'ZZPLACADEV'              => '',
            'ZZGPDEV'                 => '',
            'ZZVLTOTAL_PED'           => '',
            'ZZDTAPGTO'               => '',
            'ZZDTAENC'                => '',
            'ZZDURLOC'                => '',
            'ZZDTAINI'                => '',
            'ZZDTAFIM'                => '',
            'ZZVLTOTAL'               => '',
            'WAERK'                   => '',
            'MATNR'                   => '',
            'KWMENG'                  => '',
            'WERKS'                   => '',
            'COND_VALUE1'             => '',
            'COND_VALUE2'             => '',
            'COND_VALUE3'             => '', 
            'COND_VALUE4'             => '',
            'PRCTR'                   => '',
            'KUNNR'                   => '',
            'ZLSCH'                   => '',
            'COND_VALUE5'             => '',
            'ZZTRANSACAO'             => '',
            'ZTEXT_FORMAPGTO'         => '',
            'ZTEXT_INFO_COMPLEM'      => ''   
        ]
    ];


    public static $rules =  [ 
        'GUID'                    => '',
        'COD_INTERF'              => '',
        'TIPO_ORDEM'              => '',
        'EMISSOR'                 => '',
        'KUNNR_EMISSOR'           => '',
        'PAGADOR'                 => '',
        'KUNNR_PAGADOR'           => '',
        'AGENCIA'                 => '',
        'KUNNR_AGENCIA'           => '',
        'AG_TRIPARTITE'           => '',
        'KUNNR_AG_TRIPARTITE'     => '',
        'COND_ADICIONAL'          => '',
        'KUNNR_COND_ADICIONAL'    => '',
        'AG_ABERTURA'             => '',
        'PERNR_AG_ABERTURA'       => '',
        'AG_ENCERRAMENTO'         => '',
        'PERNR_AG_ENCERRAMENTO'   => '',
        'ZZUPGRADE'               => '',
        'ZZNRCONTRATO'            => '',
        'ZZNRPERIODO'             => '',
        'ZZNRADITIVO'             => '',
        'ZZNRRESERVA'             => '',
        'ZZTPCANAL'               => '',
        'ZZCODREF'                => '',
        'ZZDTARES'                => '',
        'ZZHRARES'                => '',
        'ZZLJRET'                 => '',
        'ZZDTARET'                => '',
        'ZZHRARET'                => '',
        'ZZPLACARET'              => '',
        'ZZGPRET'                 => '',
        'ZZLJDEV'                 => '',
        'ZZDTADEV'                => '',
        'ZZHRADEV'                => '',
        'ZZPLACADEV'              => '',
        'ZZGPDEV'                 => '',
        'ZZVLTOTAL_PED'           => '',
        'ZZDTAPGTO'               => '',
        'ZZDTAENC'                => '',
        'ZZDURLOC'                => '',
        'ZZDTAINI'                => '',
        'ZZDTAFIM'                => '',
        'ZZVLTOTAL'               => '',
        'WAERK'                   => '',
        'MATNR'                   => '',
        'KWMENG'                  => '',
        'WERKS'                   => '',
        'COND_VALUE1'             => '',
        'COND_VALUE2'             => '',
        'COND_VALUE3'             => '', 
        'COND_VALUE4'             => '',
        'PRCTR'                   => '',
        'KUNNR'                   => '',
        'ZLSCH'                   => '',
        'COND_VALUE5'             => '',
        'ZZTRANSACAO'             => '',
        'ZTEXT_FORMAPGTO'         => '',
        'ZTEXT_INFO_COMPLEM'      => ''
    ];

    public static function parse($array)
    {
        if ($array) {

            $data = [
                'GUID' => $array['GUID'],
                'DADOS_CONTRATO'              => [
                    'COD_INTERF'              => $array['COD_INTERF'],
                    'TIPO_ORDEM'              => $array['TIPO_ORDEM'],
                    'EMISSOR'                 => $array['EMISSOR'],
                    'KUNNR_EMISSOR'           => $array['KUNNR_EMISSOR'],
                    'PAGADOR'                 => $array['PAGADOR'],
                    'KUNNR_PAGADOR'           => $array['KUNNR_PAGADOR'],
                    'AGENCIA'                 => $array['AGENCIA'],
                    'KUNNR_AGENCIA'           => $array['KUNNR_AGENCIA'],
                    'AG_TRIPARTITE'           => $array['AG_TRIPARTITE'],
                    'KUNNR_AG_TRIPARTITE'     => $array['KUNNR_AG_TRIPARTITE'],
                    'COND_ADICIONAL'          => $array['COND_ADICIONAL'],
                    'KUNNR_COND_ADICIONAL'    => $array['KUNNR_COND_ADICIONAL'],
                    'AG_ABERTURA'             => $array['AG_ABERTURA'],
                    'PERNR_AG_ABERTURA'       => $array['PERNR_AG_ABERTURA'],
                    'AG_ENCERRAMENTO'         => $array['AG_ENCERRAMENTO'],
                    'PERNR_AG_ENCERRAMENTO'   => $array['PERNR_AG_ENCERRAMENTO'],
                    'ZZUPGRADE'               => $array['ZZUPGRADE'],
                    'ZZNRCONTRATO'            => $array['ZZNRCONTRATO'],
                    'ZZNRPERIODO'             => $array['ZZNRPERIODO'],
                    'ZZNRADITIVO'             => $array['ZZNRADITIVO'],
                    'ZZNRRESERVA'             => $array['ZZNRRESERVA'],
                    'ZZTPCANAL'               => $array['ZZTPCANAL'],
                    'ZZCODREF'                => $array['ZZCODREF'],
                    'ZZDTARES'                => $array['ZZDTARES'],
                    'ZZHRARES'                => $array['ZZHRARES'],
                    'ZZLJRET'                 => $array['ZZLJRET'],
                    'ZZDTARET'                => $array['ZZDTARET'],
                    'ZZHRARET'                => $array['ZZHRARET'],
                    'ZZPLACARET'              => $array['ZZPLACARET'],
                    'ZZGPRET'                 => $array['ZZGPRET'],
                    'ZZLJDEV'                 => $array['ZZLJDEV'],
                    'ZZDTADEV'                => $array['ZZDTADEV'],
                    'ZZHRADEV'                => $array['ZZHRADEV'],
                    'ZZPLACADEV'              => $array['ZZPLACADEV'],
                    'ZZGPDEV'                 => $array['ZZGPDEV'],
                    'ZZVLTOTAL_PED'           => $array['ZZVLTOTAL_PED'],
                    'ZZDTAPGTO'               => $array['ZZDTAPGTO'],
                    'ZZDTAENC'                => $array['ZZDTAENC'],
                    'ZZDURLOC'                => $array['ZZDURLOC'],
                    'ZZDTAINI'                => $array['ZZDTAINI'],
                    'ZZDTAFIM'                => $array['ZZDTAFIM'],
                    'ZZVLTOTAL'               => $array['ZZVLTOTAL'],
                    'WAERK'                   => $array['WAERK'],
                    'MATNR'                   => $array['MATNR'],
                    'KWMENG'                  => $array['KWMENG'],
                    'WERKS'                   => $array['WERKS'],
                    'COND_VALUE1'             => $array['COND_VALUE1'],
                    'COND_VALUE2'             => $array['COND_VALUE2'],
                    'COND_VALUE3'             => $array['COND_VALUE3'], 
                    'COND_VALUE4'             => $array['COND_VALUE4'],
                    'PRCTR'                   => $array['PRCTR'],
                    'KUNNR'                   => $array['KUNNR'],
                    'ZLSCH'                   => $array['ZLSCH'],
                    'COND_VALUE5'             => $array['COND_VALUE5'],
                    'ZZTRANSACAO'             => $array['ZZTRANSACAO'],
                    'ZTEXT_FORMAPGTO'         => $array['ZTEXT_FORMAPGTO'],
                    'ZTEXT_INFO_COMPLEM'      => $array['ZTEXT_INFO_COMPLEM']   
                ]
            ];
        }

        return $data;
    }
}