<?php

namespace App\Requests;

use Validator;

class EncerramentoDeContratoRule {

    public static $endpoint = 'EncerramentoContrato_I013';

    protected static $request = [
        'GUID'                        => '',
        'DADOS_CONTRATO'              => [
            'COD_INTERF'              => '',
            'TIPO_ORDEM'              => '',
            'EMISSOR'                 => '',
            'KUNNR_EMISSOR'           => '',
            'PAGADOR'                 => '',
            'KUNNR_PAGADOR'           => '',
            'AGENCIA'                 => '',
            'KUNNR_AGENCIA'           => '',
            'AG_TRIPARTITE'           => '',
            'KUNNR_AG_TRIPARTITE'     => '',
            'COND_ADICIONAL'          => '',
            'KUNNR_COND_ADICIONAL'    => '',
            'AG_ABERTURA'             => '',
            'PERNR_AG_ABERTURA'       => '',
            'AG_ENCERRAMENTO'         => '',
            'PERNR_AG_ENCERRAMENTO'   => '',
            'ZZUPGRADE'               => '',
            'ZZNRCONTRATO'            => '',
            'ZZNRPERIODO'             => '',
            'ZZNRADITIVO'             => '',
            'ZZNRRESERVA'             => '',
            'ZZTPCANAL'               => '',
            'ZZCODREF'                => '',
            'ZZDTARES'                => '',
            'ZZHRARES'                => '',
            'ZZLJRET'                 => '',
            'ZZDTARET'                => '',
            'ZZHRARET'                => '',
            'ZZPLACARET'              => '',
            'ZZGPRET'                 => '',
            'ZZLJDEV'                 => '',
            'ZZDTADEV'                => '',
            'ZZHRADEV'                => '',
            'ZZPLACADEV'              => '',
            'ZZGPDEV'                 => '',
            'ZZVLTOTAL_PED'           => '',
            'ZZDTAPGTO'               => '',
            'ZZDTAENC'                => '',
            'ZZDURLOC'                => '',
            'ZZDTAINI'                => '',
            'ZZDTAFIM'                => '',
            'ZZVLTOTAL'               => '',
            'WAERK'                   => '',
            'MATNR'                   => '',
            'KWMENG'                  => '',
            'WERKS'                   => '',
            'COND_VALUE1'             => '',
            'COND_VALUE2'             => '',
            'COND_VALUE3'             => '', 
            'COND_VALUE4'             => '',
            'PRCTR'                   => '',
            'KUNNR'                   => '',
            'ZLSCH'                   => '',
            'COND_VALUE5'             => '',
            'ZZTRANSACAO'             => '',
            'ZTEXT_FORMAPGTO'         => '',
            'ZTEXT_INFO_COMPLEM'      => ''   
        ]
    ];


    public static $rules =  [ 
        'GUID'                    => '',
        'COD_INTERF'              => '',
        'TIPO_ORDEM'              => '',
        'EMISSOR'                 => '',
        'KUNNR_EMISSOR'           => '',
        'PAGADOR'                 => '',
        'KUNNR_PAGADOR'           => '',
        'AGENCIA'                 => '',
        'KUNNR_AGENCIA'           => '',
        'AG_TRIPARTITE'           => '',
        'KUNNR_AG_TRIPARTITE'     => '',
        'COND_ADICIONAL'          => '',
        'KUNNR_COND_ADICIONAL'    => '',
        'AG_ABERTURA'             => '',
        'PERNR_AG_ABERTURA'       => '',
        'AG_ENCERRAMENTO'         => '',
        'PERNR_AG_ENCERRAMENTO'   => '',
        'ZZUPGRADE'               => '',
        'ZZNRCONTRATO'            => '',
        'ZZNRPERIODO'             => '',
        'ZZNRADITIVO'             => '',
        'ZZNRRESERVA'             => '',
        'ZZTPCANAL'               => '',
        'ZZCODREF'                => '',
        'ZZDTARES'                => '',
        'ZZHRARES'                => '',
        'ZZLJRET'                 => '',
        'ZZDTARET'                => '',
        'ZZHRARET'                => '',
        'ZZPLACARET'              => '',
        'ZZGPRET'                 => '',
        'ZZLJDEV'                 => '',
        'ZZDTADEV'                => '',
        'ZZHRADEV'                => '',
        'ZZPLACADEV'              => '',
        'ZZGPDEV'                 => '',
        'ZZVLTOTAL_PED'           => '',
        'ZZDTAPGTO'               => '',
        'ZZDTAENC'                => '',
        'ZZDURLOC'                => '',
        'ZZDTAINI'                => '',
        'ZZDTAFIM'                => '',
        'ZZVLTOTAL'               => '',
        'WAERK'                   => '',
        'MATNR'                   => '',
        'KWMENG'                  => '',
        'WERKS'                   => '',
        'COND_VALUE1'             => '',
        'COND_VALUE2'             => '',
        'COND_VALUE3'             => '', 
        'COND_VALUE4'             => '',
        'PRCTR'                   => '',
        'KUNNR'                   => '',
        'ZLSCH'                   => '',
        'COND_VALUE5'             => '',
        'ZZTRANSACAO'             => '',
        'ZTEXT_FORMAPGTO'         => '',
        'ZTEXT_INFO_COMPLEM'      => ''
    ];
    
    public static function parse($array)
    {
        if ($array) {

            $data = [
               'GUID'           => $array['GUID'],
               'COD_INTERF'     => $array['COD_INTERF'],
               'VBELN'          => $array['VBELN'],
               'ZZTPCLIENTE'    => $array['ZZTPCLIENTE'],
               'ZZUPGRADE'      => $array['ZZUPGRADE'],
               'ZZNRCONTRATO'   => $array['ZZNRCONTRATO'],
               'ZZNRPERIODO'    => $array['ZZNRPERIODO'],
               'ZZNRADITIVO'    => $array['ZZNRADITIVO'],
               'ZZNRRESERVA'    => $array['ZZNRRESERVA'],
               'ZZTPCANAL'      => $array['ZZTPCANAL'],
               'ZZCODREF'       => $array['ZZCODREF'],
               'ZZDTARES'       => $array['ZZDTARES'],
               'ZZHRARES'       => $array['ZZHRARES'],
               'ZZLJRET'        => $array['ZZLJRET'],
               'ZZDTARET'       => $array['ZZDTARET'],
               'ZZHRARET'       => $array['ZZHRARET'],
               'ZZPLACARET'     => $array['ZZPLACARET'],
               'ZZGPRET'        => $array['ZZGPRET'],
               'ZZLJDEV'        => $array['ZZLJDEV'],
               'ZZDTADEV'       => $array['ZZDTADEV'],
               'ZZHRADEV'       => $array['ZZHRADEV'],
               'ZZPLACADEV'     => $array['ZZPLACADEV'],
               'ZZGPDEV'        => $array['ZZGPDEV'],
               'ZZVLTOTAL_PED'  => $array['ZZVLTOTAL_PED'],
               'ZZDTAPGTO'      => $array['ZZDTAPGTO'],
               'ZZDTAENC'       => $array['ZZDTAENC'],
               'ZZDURLOC'       => $array['ZZDURLOC'],
               'ZZDTAINI'       => $array['ZZDTAINI'],
               'ZZDTAFIM'       => $array['ZZDTAFIM'],
               'ZZVLTOTAL'      => $array['ZZVLTOTAL'],
               'AUGRU'              => $array['AUGRU'],
               'ZZDENTREG'          => $array['ZZDENTREG'],
               'WAERK'              => $array['WAERK'],
               'ZTEXT_FORMAPGTO'    => $array['ZTEXT_FORMAPGTO'],
               'ZTEXT_INFO_COMPLEM' => $array['ZTEXT_INFO_COMPLEM'],
               //Loop de Itens
               'ITENS'  => [
                   'MATNR'          => $array['MATNR'], 
                   'KWMENG'         => $array['KWMENG'],
                   'WERKS'          => $array['WERKS'],
                   'COND_VALUE1'    => $array['COND_VALUE1'],
                   'COND_VALUE2'    => $array['COND_VALUE2'],
                   'COND_VALUE3'    => $array['COND_VALUE3'],
                   'COND_VALUE4'    => $array['COND_VALUE4'],
                   'COND_VALUE6'    => $array['COND_VALUE6'],
                   'PRCTR'          => $array['PRCTR']
               ],
               //Loop de Parceiros
               'PARCEIROS'  => [
                   'PARVW'    => $array['PARVW'], 
                   'KUNNR'    => $array['KUNNR']
               ],
            ];
        }

        return $data;
    }
}